### ISSUE TITLE
can't compile the mmal branch with actual ffmpeg

### ISSUE THREAD

**Issue by dbloms** [zillevdr/vdr-plugin-softhddevice#1]
I try to compile the mmal branch on my raspberry3 running with raspbian (stretch).
I use ffmpeg from actual git (https://github.com/FFmpeg/FFmpeg) commit 9c35285aea84be916ab19a1ed3627afaad461199.
When I try to compile vdr-plugin-softhddevice-drm for vdr 2.3.7, I get the following error messages:
https://pastebin.com/wE85WfqM

**Comment by zillevdr** [comment]
Please use an older version of ffmpeg. I use ffmpeg-3.2. In the next weeks this branch became obsolete. I work on v4l2. Than a newer version of ffmpeg can be used.

**Comment by dbloms** [comment]
Oh, that is sad, that this branch becomes obsolete, because I'd like to use softhddevice on my raspberry.
Or is there another solution I can use ?

**Comment by zillevdr** [comment]
I work to integrate v4l2 ABI in to master. Then Raspi can use master and mmal is obsolete. Success with an older ffmpeg?

**Comment by dbloms** [comment]
Ok, that good news ;)
No, I had no success. With 3.2 I can't compile this plugin. I got soemthing like "undefined symbol: avcodec_default_release_buffer". But this doesn't matter, if there is a working master branch for raspberry

**Comment by zillevdr** [comment]
Please use master branch. There is now mmal suport. Switch MMAL in Makefile to 1 for that.
