### ISSUE TITLE
Mediaplayer, support stop and exit (from remote)

### ISSUE THREAD

**Issue by MarkusEh** [zillevdr/vdr-plugin-softhddevice#10]
Hi,

I can stop the video with menu->"stop recording".
Would it be possible to also support the remote (stop key)?

For the "exit" key during reply of media, could you implement a similar behavior as VDR for recordings: Display the list of video files, from which the currently playing file was selected.

Thanks and Regards, Markus

**Comment by zillevdr** [comment]
Hi Markus,

it's like dvbplayer from vdr it does. The player stop if you press the blue button. OK button open the progress bar. Open the softhddevice-drm menu entry while playing a playlist you see the actual playlist.
