### ISSUE TITLE
VideoOsdClear render not always available

### ISSUE THREAD

**Issue by rofehr** [zillevdr/vdr-plugin-softhddevice#3]
change function to

void VideoOsdClear(VideoRender * render)
{
    if(render)
    {
	if (render->use_zpos) {
		ChangePlanes(render, 1);
		memset((void *)render->buf_osd.plane[0], 0,
			(size_t)(render->buf_osd.pitch[0] * render->buf_osd.height));
	} else {
		if (drmModeSetPlane(render->fd_drm, render->osd_plane, render->crtc_id, 0, 0,
			0, 0, render->buf_osd.width, render->buf_osd.height, 0, 0, 0 << 16, 0 << 16))
				fprintf(stderr, "VideoOsdClear: failed to clear plane: (%d): %m\n", (errno));
		render->buf_osd.x = 0;
	}
    }
}

**Comment by zillevdr** [comment]
This should be fixed where it came from. The skin plugin do something wrong.
