### ISSUE TITLE
Segfault in function unsigned int ReadBit()

### ISSUE THREAD

**Issue by rofehr** [zillevdr/vdr-plugin-softhddevice#4]
m_pStart 
is not initialized

![grafik](https://user-images.githubusercontent.com/11458774/112203834-3d8f4980-8c13-11eb-8abc-dee92aca5124.png)

**Comment by rofehr** [comment]
Hier mal der CallStack
![grafik](https://user-images.githubusercontent.com/11458774/112204471-fce40000-8c13-11eb-9865-6cc59453f7ae.png)

**Comment by zillevdr** [comment]
ParseResolution does only work with an ES. What data do you use? Can I get a small piece inclusive index,... of that?

**Comment by rofehr** [comment]
It is a Stream from the OctopusNet SatIP Server.

**Comment by rofehr** [comment]
Wrong ffmepg version :(
