### ISSUE TITLE
avi files support

### ISSUE THREAD

**Issue by redblue-pkt** [zillevdr/vdr-plugin-softhddevice#5]
Hello,
Your plugin works great for neutrino-mp in orangepi lite2 or orangepi one plus. However, image stuttering occurs when playing avi files. Probably incorrect pts is to blame. Can you do something about it?

**Comment by zillevdr** [comment]
I don't use avi files. Can I get a small file to check it?

**Comment by redblue-pkt** [comment]
http://samples.mplayerhq.hu/avi/GoneNutty.avi

**Comment by zillevdr** [comment]
I tested the file and it plays more or less. Inside the file are only pts for audio. No pts for video. But both pts are necessary to synchronize audio and video. So the mediaplayer must play it without sync. The picture will presented as it comes. I can't do anything without correct data. I think *.avi shouldn't add to TestMedia().

**Comment by redblue-pkt** [comment]
And dts won't help? In avi files I think dts = pts. How to disable this audio video sync in your plugin?

**Comment by zillevdr** [comment]
I doesn't look into dts. But dts is only for decoder. There are codecs with an other order of packets as the order for presentation.
If the time difference between audio and video is more than 5 seconds both run without synchronisation.
FFmpeg have a flag AVFMT_FLAG_GENPTS. I don't know now how does it work. I will look into that.

**Comment by redblue-pkt** [comment]
`FrameDuped Pkts 103 deint 1 Frames 3 AudioUsedBytes 1486476 audio  0:00:03.174 video  0:00:03.211 Delay 0ms diff 37ms
FrameDuped Pkts 94 deint 0 Frames 3 AudioUsedBytes 1485432 audio  0:00:03.634 video  0:00:03.670 Delay 0ms diff 36ms
loop:1251 msg->MP: 80000014, data: 00000006
playback:GetPosition 2000 1549000
CMoviePlayerGui::UpdatePosition: spd 1 pos 3000/1549000 (1546000, 0%)
[3823.553][925 rtsp.cpp            : 702][handleRTSPStatus         ]	 debug: RTSP STATUS : RTSP_STATUS_CONFIG_WAITING
[3823.577][925 vtuner.cpp          : 636][vtunerEvent              ]	 debug: MSG_UNKNOWN: 195
[3823.577][925 rtsp.cpp            : 702][handleRTSPStatus         ]	 debug: RTSP STATUS : RTSP_STATUS_CONFIG_WAITING
FrameDuped Pkts 80 deint 1 Frames 3 AudioUsedBytes 1484784 audio  0:00:04.133 video  0:00:04.170 Delay 0ms diff 37ms
FrameDuped Pkts 68 deint 2 Frames 3 AudioUsedBytes 1474920 audio  0:00:04.593 video  0:00:04.629 Delay 0ms diff 36ms
loop:1251 msg->MP: 80000014, data: 00000006
playback:GetPosition 3000 1549000
CMoviePlayerGui::UpdatePosition: spd 1 pos 4000/1549000 (1545000, 0%)
[3824.577][925 rtsp.cpp            : 702][handleRTSPStatus         ]	 debug: RTSP STATUS : RTSP_STATUS_CONFIG_WAITING
[3824.601][925 vtuner.cpp          : 636][vtunerEvent              ]	 debug: MSG_UNKNOWN: 195
[3824.601][925 rtsp.cpp            : 702][handleRTSPStatus         ]	 debug: RTSP STATUS : RTSP_STATUS_CONFIG_WAITING
FrameDuped Pkts 57 deint 1 Frames 3 AudioUsedBytes 1478880 audio  0:00:05.094 video  0:00:05.130 Delay 0ms diff 36ms
FrameDuped Pkts 44 deint 2 Frames 3 AudioUsedBytes 1478232 audio  0:00:05.593 video  0:00:05.630 Delay 0ms diff 37ms
loop:1251 msg->MP: 80000014, data: 00000006
playback:GetPosition 4000 1549000
CMoviePlayerGui::UpdatePosition: spd 1 pos 5000/1549000 (1544000, 0%)
[3825.601][925 rtsp.cpp            : 702][handleRTSPStatus         ]	 debug: RTSP STATUS : RTSP_STATUS_CONFIG_WAITING
[3825.625][925 vtuner.cpp          : 636][vtunerEvent              ]	 debug: MSG_UNKNOWN: 195
[3825.625][925 rtsp.cpp            : 702][handleRTSPStatus         ]	 debug: RTSP STATUS : RTSP_STATUS_CONFIG_WAITING
FrameDuped Pkts 35 deint 1 Frames 3 AudioUsedBytes 1486404 audio  0:00:06.053 video  0:00:06.089 Delay 0ms diff 36ms
FrameDuped Pkts 21 deint 1 Frames 3 AudioUsedBytes 1476936 audio  0:00:06.594 video  0:00:06.631 Delay 0ms diff 37ms
playback:GetPosition 5000 1549000
CMoviePlayerGui::PlayFileLoop: spd 1 pos 6000/1549000 (1543000, 0%)
[3826.625][925 rtsp.cpp            : 702][handleRTSPStatus         ]	 debug: RTSP STATUS : RTSP_STATUS_CONFIG_WAITING
[3826.649][925 vtuner.cpp          : 636][vtunerEvent              ]	 debug: MSG_UNKNOWN: 195
[3826.649][925 rtsp.cpp            : 702][handleRTSPStatus         ]	 debug: RTSP STATUS : RTSP_STATUS_CONFIG_WAITING
FrameDuped Pkts 9 deint 2 Frames 3 AudioUsedBytes 1475892 audio  0:00:07.054 video  0:00:07.090 Delay 0ms diff 36ms
FrameDuped Pkts 0 deint 0 Frames 2 AudioUsedBytes 1475244 audio  0:00:07.553 video  0:00:07.590 Delay 0ms diff 37ms
playback:GetPosition 6000 1549000
CMoviePlayerGui::PlayFileLoop: spd 1 pos 7000/1549000 (1542000, 0%)
FrameDropped Pkts 0 deint 0 Frames 1 AudioUsedBytes 1485648 audio  0:00:07.733 video  0:00:07.716 Delay 0ms diff -17ms
FrameDropped Pkts 0 deint 0 Frames 2 AudioUsedBytes 1477224 audio  0:00:07.794 video  0:00:07.716 Delay 0ms diff -78ms
FrameDropped Pkts 0 deint 0 Frames 1 AudioUsedBytes 1477224 audio  0:00:07.794 video  0:00:07.757 Delay 0ms diff -37ms
FrameDropped Pkts 0 deint 0 Frames 1 AudioUsedBytes 1486440 audio  0:00:07.815 video  0:00:07.757 Delay 0ms diff -58ms
FrameDropped Pkts 0 deint 0 Frames 1 AudioUsedBytes 1486836 audio  0:00:07.866 video  0:00:07.799 Delay 0ms diff -67ms
[3827.649][925 rtsp.cpp            : 702][handleRTSPStatus         ]	 debug: RTSP STATUS : RTSP_STATUS_CONFIG_WAITING
FrameDropped Pkts 0 deint 0 Frames 1 AudioUsedBytes 1487232 audio  0:00:07.925 video  0:00:07.799 Delay 0ms diff -126ms
[3827.673][925 vtuner.cpp          : 636][vtunerEvent              ]	 debug: MSG_UNKNOWN: 195
[3827.673][925 rtsp.cpp            : 702][handleRTSPStatus         ]	 debug: RTSP STATUS : RTSP_STATUS_CONFIG_WAITING
FrameDropped Pkts 0 deint 0 Frames 2 AudioUsedBytes 1487628 audio  0:00:07.976 video  0:00:07.841 Delay 0ms diff -135ms
FrameDropped Pkts 0 deint 0 Frames 1 AudioUsedBytes 1487628 audio  0:00:07.976 video  0:00:07.841 Delay 0ms diff -135ms
FrameDropped Pkts 0 deint 0 Frames 1 AudioUsedBytes 1483812 audio  0:00:08.077 video  0:00:07.882 Delay 0ms diff -195ms
FrameDropped Pkts 0 deint 0 Frames 1 AudioUsedBytes 1483812 audio  0:00:08.087 video  0:00:07.882 Delay 0ms diff -205ms
FrameDropped Pkts 0 deint 0 Frames 1 AudioUsedBytes 1484208 audio  0:00:08.138 video  0:00:07.924 Delay 0ms diff -214ms
FrameDropped Pkts 0 deint 0 Frames 1 AudioUsedBytes 1484604 audio  0:00:08.187 video  0:00:07.924 Delay 0ms diff -263ms
FrameDropped Pkts 0 deint 0 Frames 1 AudioUsedBytes 1485000 audio  0:00:08.208 video  0:00:07.966 Delay 0ms diff -242ms
FrameDropped Pkts 0 deint 0 Frames 2 AudioUsedBytes 1485396 audio  0:00:08.269 video  0:00:07.966 Delay 0ms diff -303ms
`
I added this flag to your code, and avi files still don't work properly.

**Comment by zillevdr** [comment]
Genpts isn't a solution. I test an other way. Calculate the pts and don't use the pts from file. It looks good. But I need time for that. It's just a hobby.

**Comment by redblue-pkt** [comment]
The problem of avi files has been resolved. Thank you. Of course, the AVFMT_FLAG_GENPTS flag is required.
