### ISSUE TITLE
frames dropping and "slow" audio on rpi4

### ISSUE THREAD

**Issue by chaseadam** [zillevdr/vdr-plugin-softhddevice#7]
Thanks for maintaining this project!

Attempting to play an ATSC broadcast (MPEG2) on Raspberry Pi 4.

audio consistently "slow" throughout this loop

Behavior in order:
* lots of dropped frames
* small period of smooth playback
* blank screen for a second or two
* repeat

My hypothesis is an audio issue is causing the video playback problem. There are audio errors in STDOUT (see below).

[Here is a video of the behavior starting with a split second of smooth playback](https://ipfs.io/ipfs/QmT1paYYVzxBtEN1RxzevmXVYajdL6vyzSm95ine2RCoEu?filename=VID_20211119_113354.mp4)

### Environment
Model details: 2GB with heat sink and fan, OEM power adapter

Tuner card is WinTV-HVR-950Q USB based (tried plugged into USB3 and USB2 ports).

Load is a bit high, but expected with software decoding

```
pi@raspberrypi:~/git/vdr $ uptime
 11:30:52 up  1:20,  3 users,  load average: 2.95, 2.80, 1.66
```

Free RAM seems fine:

```
pi@raspberrypi:~/git/vdr $ free
               total        used        free      shared  buff/cache   available
Mem:         1894304      276356      425952        1172     1191996     1547332
Swap:         102396         256      102140
```

RaspiOS x86_64 https://downloads.raspberrypi.org/raspios_arm64/images/raspios_arm64-2021-11-08/

```
pi@raspberrypi:~/git/vdr $ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```

Compiled fresh checkouts from default branches:
https://github.com/zillevdr/vdr-plugin-softhddevice-drm.git f32c44d1e1fd5b568915db8b16b6371a1506bab8
git://git.tvdr.de/vdr.git 0d50ec57f50375c8fda92d117e348dd8fd5a77a9

VDR stdout:

```
pi@raspberrypi:/var/lib/vdr $ sudo vdr -P'softhddevice-drm' --log=3
AlsaPlayer: ring buffer empty
AlsaPlayer: ring buffer empty
AlsaPlayer: ring buffer empty
AlsaPlayer: ring buffer empty
AlsaPlayer: ring buffer empty
AlsaPlayer: ring buffer empty
AlsaPlayer: ring buffer empty
AlsaPlayer: ring buffer empty
AlsaPlayer: ring buffer empty
AlsaPlayer: ring buffer empty
AlsaPlayer: ring buffer empty
AlsaPlayer: ring buffer empty
AlsaPlayer: ring buffer empty
AlsaPlayer: ring buffer empty
AlsaPlayer: ring buffer empty
AlsaPlayer: ring buffer empty
AlsaPlayer: ring buffer empty
AlsaPlayer: ring buffer empty
AlsaPlayer: ring buffer empty
AlsaPlayer: ring buffer empty
AlsaPlayer: ring buffer empty
VideoRenderFrame: error_flag or FRAME_FLAG_CORRUPT
AlsaPlayer: ring buffer empty
AlsaPlayer: ring buffer empty
AlsaPlayer: ring buffer empty
```

Debug logs:

```
Nov 19 16:20:51 raspberrypi vdr: [12439] VDR version 2.5.6 started
Nov 19 16:20:51 raspberrypi vdr: [12439] codeset is 'UTF-8' - known
Nov 19 16:20:51 raspberrypi vdr: [12439] loading plugin: /usr/local/lib/vdr/libvdr-softhddevice-drm.so.2.5.6
Nov 19 16:20:51 raspberrypi vdr: [12439] loading /var/lib/vdr/setup.conf
Nov 19 16:20:51 raspberrypi vdr: [12439] loading /var/lib/vdr/sources.conf
Nov 19 16:20:51 raspberrypi vdr: [12439] loading /var/lib/vdr/diseqc.conf
Nov 19 16:20:51 raspberrypi vdr: [12439] loading /var/lib/vdr/scr.conf
Nov 19 16:20:51 raspberrypi vdr: [12439] loading /var/lib/vdr/channels.conf
Nov 19 16:20:51 raspberrypi vdr: [12439] loading /var/lib/vdr/timers.conf
Nov 19 16:20:51 raspberrypi vdr: [12439] loading /var/lib/vdr/svdrphosts.conf
Nov 19 16:20:51 raspberrypi vdr: [12439] loading /var/lib/vdr/keymacros.conf
Nov 19 16:20:51 raspberrypi vdr: [12439] loading /var/lib/vdr/camresponses.conf
Nov 19 16:20:51 raspberrypi kernel: [ 4216.346740] au0828: Enabled Source: Xceive XC5000->Auvitek AU8522 QAM/8VSB Frontend->Auvitek AU8522 QAM/8VSB Frontend Ret 0
Nov 19 16:20:53 raspberrypi kernel: [ 4218.117949] xc5000: Firmware dvb-fe-xc5000-1.6.114.fw loaded and running.
Nov 19 16:20:53 raspberrypi kernel: [ 4218.118681] au0828: Disabled Source: Xceive XC5000->Auvitek AU8522 QAM/8VSB Frontend->Auvitek AU8522 QAM/8VSB Frontend Ret 0
Nov 19 16:20:53 raspberrypi kernel: [ 4218.118751] au0828: Enabled Source: Xceive XC5000->Auvitek AU8522 QAM/8VSB Frontend->Auvitek AU8522 QAM/8VSB Frontend Ret 0
Nov 19 16:20:53 raspberrypi vdr: [12439] DVB API version is 0x050B (VDR was built with 0x050B)
Nov 19 16:20:53 raspberrypi vdr: [12439] frontend 0/0 provides ATSC,DVB-C with QAM64,QAM256,VSB8 ("Auvitek AU8522 QAM/8VSB Frontend")
Nov 19 16:20:53 raspberrypi vdr: [12439] found 1 DVB device
Nov 19 16:20:53 raspberrypi vdr: [12439] initializing plugin: softhddevice-drm (0.0.1rc1-GITf32c44d): A software and GPU emulated HD device
Nov 19 16:20:53 raspberrypi vdr: [12439] setting primary device to 2
Nov 19 16:20:53 raspberrypi vdr: [12439] setting current skin to "lcars"
Nov 19 16:20:53 raspberrypi vdr: [12439] loading /var/lib/vdr/themes/lcars-default.theme
Nov 19 16:20:53 raspberrypi vdr: [12439] starting plugin: softhddevice-drm
Nov 19 16:21:03 raspberrypi vdr: [12439] switching to channel 1 A-0-491-3 (WRAL HD)
Nov 19 16:21:03 raspberrypi vdr: [12449] SVDRP raspberrypi opening port 6419/tcp
Nov 19 16:21:03 raspberrypi vdr: [12449] SVDRP raspberrypi listening on port 6419/tcp
Nov 19 16:21:05 raspberrypi vdr: [12439] retuning due to modification of channel 1 (WRAL HD)
Nov 19 16:21:05 raspberrypi vdr: [12439] switching to channel 1 A-0-491-3 (WRAL HD)
```

Tuner logs

```
[   65.376483] au0828: Enabled Source: Xceive XC5000->Auvitek AU8522 QAM/8VSB Frontend->Auvitek AU8522 QAM/8VSB Frontend Ret 0
[   68.494484] xc5000: Firmware dvb-fe-xc5000-1.6.114.fw loaded and running.
[   68.495792] au0828: Disabled Source: Xceive XC5000->Auvitek AU8522 QAM/8VSB Frontend->Auvitek AU8522 QAM/8VSB Frontend Ret 0
```

Original discussion on MLD forums: https://minidvblinux.de/forum/index.php/topic,10261.msg81552.html

**Comment by chaseadam** [comment]
attempt to send audio to a "dummy" device did not change video behavior and there is still the occasional `AlsaPlayer: ring buffer empty` error in STDOUT.

Over time the load exceeds 3, so maybe there just isn't enough power in the raspberry pi to do everything in software?

```
pi@raspberrypi:~/git/vdr $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: Headphones [bcm2835 Headphones], device 0: bcm2835 Headphones [bcm2835 Headphones]
  Subdevices: 7/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7
card 1: vc4hdmi0 [vc4-hdmi-0], device 0: MAI PCM i2s-hifi-0 [MAI PCM i2s-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: vc4hdmi1 [vc4-hdmi-1], device 0: MAI PCM i2s-hifi-0 [MAI PCM i2s-hifi-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 4: Dummy [Dummy], device 0: Dummy PCM [Dummy PCM]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice #1: subdevice #1
  Subdevice #2: subdevice #2
  Subdevice #3: subdevice #3
  Subdevice #4: subdevice #4
  Subdevice #5: subdevice #5
  Subdevice #6: subdevice #6
  Subdevice #7: subdevice #7

pi@raspberrypi:/var/lib/vdr $ sudo vdr -P'softhddevice-drm -a hw:4,0' --log=3
AlsaPlayer: ring buffer empty
AlsaPlayer: ring buffer empty
```

**Comment by chaseadam** [comment]
playing a `.ts` recording of the broadcast also results in the same behavior, so that removes the tuner as an issue.

```
pi@raspberrypi:~/git/vdr $ svdrpsend plug softhddevice-drm PLAY /home/pi/foo.ts 
220 raspberrypi SVDRP VideoDiskRecorder 2.5.6; Fri Nov 19 12:09:28 2021; UTF-8
900 PLAY url
221 raspberrypi closing connection
```

An attempt to play an `.mp3` results in repeated errors in STDOUT

```
pi@raspberrypi:~/git/vdr $ svdrpsend plug softhddevice-drm PLAY /home/pi/foo.mp3
220 raspberrypi SVDRP VideoDiskRecorder 2.5.6; Fri Nov 19 12:15:16 2021; UTF-8
900 PLAY url
221 raspberrypi closing connection

pi@raspberrypi:/var/lib/vdr $ sudo vdr -P'softhddevice-drm' --log=3
AlsaSetup: set params error: File descriptor in bad state
AudioGetClock: no hw delay
AudioGetClock: no hw delay
...
```
(also mentioned in https://minidvblinux.de/forum/index.php/topic,10209.msg81141.html?PHPSESSID=kelu3d9g4fgc1jgluskrsmsad6#msg81141)

I can get smooth playback with `svdrpsend plug softhddevice-drm PLAY https://file-examples-com.github.io/uploads/2017/04/file_example_MP4_1920_18MG.mp4` *only if I use the dummy alsa sink*. If using analog audio sink, I get repeating `AudioGetClock: no hw delay` and video frozen on first frame.

**Comment by zillevdr** [comment]
Your video have a broken audio stream. I can't hear anything. Also the audio PTS isn' right. The video was synchronized to the wrong audio PTS. That's why much video frames are twice presented. Can I get a raw TS recording from vdr?

**Comment by chaseadam** [comment]
Thanks for chiming in! Here is a recording file from a ["testing" MLD installation](http://www.minidvblinux.de/download/5.5?class=testing) of VDR with softhddevice plugin on a RPI4:
https://ipfs.io/ipfs/QmYpbnrLGQvFha24Do7STHaUY6Hef1E5SNqAwQYPCrBSgd

The audio is very faint because it was recorded via headphones to the mic on the phone camera I took the video with, but I have seen complaints from various tools about the TS recordings from the tuner card before. Specifically from mplayer:

```
➜  2021-11-22.19.44.10-0.rec mplayer 00001.ts 
MPlayer SVN-r38302-11 (C) 2000-2021 MPlayer Team
...
Playing 00001.ts.
libavformat version 58.76.100 (external)
Mismatching header version 58.73.100
TS file format detected.
VIDEO MPEG2(pid=49) AUDIO A52(pid=53) NO SUBS (yet)!  PROGRAM N. 132
VIDEO:  MPEG2  1920x1080  (aspect 3)  29.970 fps  16619.2 kbps (2077.4 kbyte/s)
...
Starting playback...
Bad stream state, please report as bug!
Movie-Aspect is undefined - no prescaling applied.
VO: [xv] 1920x1080 => 1920x1080 Planar YV12 
[mpeg2video @ 0x7fcf2aed0ee0]skipped MB in I-frame at 59 1
[mpeg2video @ 0x7fcf2aed0ee0]skipped MB in I-frame at 75 15
[mpeg2video @ 0x7fcf2aed0ee0]Warning MVs not available
[mpeg2video @ 0x7fcf2aed0ee0]concealing 204 DC, 204 AC, 204 MV errors in I frame
Bad stream state, please report as bug!
Bad stream state, please report as bug!
Movie-Aspect is 1.78:1 - prescaling to correct movie aspect.
VO: [xv] 1920x1080 => 1920x1080 Planar YV12 
[ASPECT] Warning: No suitable new res found!
[ASPECT] Warning: No suitable new res found!
A:3954.7 V:3955.2 A-V: -0.527 ct:  0.000   3/  3 ??% ??% ??,?% 0 0                                         
Bad stream state, please report as bug!
A:3954.7 V:3955.2 A-V: -0.557 ct: -0.003   4/  4 ??% ??% ??,?% 0 0                                         
Bad stream state, please report as bug!
A:3954.7 V:3955.3 A-V: -0.581 ct: -0.007   5/  5 ??% ??% ??,?% 0 0
... repeating
```

The signal on this station is strong. Seems there is a bug in dvb-tools (or the tuner) where the stats max out with the following:

```
MLD> dvb-fe-tool --femon
Lock   (0x1f) Signal= 71.43% C/N= 0.38% UCB= 250 postBER= 0
Lock   (0x1f) Signal= 71.43% C/N= 0.38% UCB= 250 postBER= 0
Lock   (0x1f) Signal= 71.43% C/N= 0.38% UCB= 250 postBER= 0
```

**Comment by zillevdr** [comment]
The TS are a MPEG2 1920x1080 interlaced video. The Raspi4 have no hardware MPEG2 decoder and no hardware deinterlacer. For decoding and deinterlacing a 1920x1080 video with software are the Raspi4 not powerfull enough. Please use an other Board! I tested your stream with Rockchip and Allwinner boards with hardware decoder and hardware deinterlacer. Both works fine.

**Comment by chaseadam** [comment]
That makes sense. I have a pine64 board with an A64  which appears to have the MPEG2 and deinterlace support in the VPU.

Interesting that the xine output plugin appears to work, but my guess is that it has a lot of code to gracefully deal with 'insufficient' hardware for playback.

**Comment by chaseadam** [comment]
I have a Pine64+ Allwinner A64 board which appears to experience the same behavior. SD stream appears to be fine, but the HD stream has the same behavior.

Audio is not working yet on the board, but that is lower level issue.

I am not seeing the OSD. I see "learning keys" in the logs, so maybe that prevents the OSD from showing.

Using armbian and compiling VDR and plugin from source. Any tricks or advice for debugging if it is using the hardware acceleration or not?

**My guess is I am missing https://github.com/bootlin/libva-v4l2-request in this distro.**

`sudo vdr -Psofthddevice-drm -l3`

[vdr.log](https://github.com/zillevdr/vdr-plugin-softhddevice-drm/files/7621144/vdr.log)
`

**Comment by zillevdr** [comment]
softhddevice-drm use ffmpeg for v4l2-request. Not libva. I'am not familiar with armbian. I use Gentoo. LibreELEC use also ffmpeg. [There](https://github.com/LibreELEC/LibreELEC.tv/tree/master/packages/multimedia/ffmpeg/patches) you need all patches in ffmpeg inside v4l2-drmprime and v4l2-request. [This](https://github.com/LibreELEC/LibreELEC.tv/tree/master/projects/Allwinner/patches/ffmpeg) patches you need also. I don't know the patchlevel from the armbian Kernel. I use linux-5.15.5 with [this patches](https://github.com/LibreELEC/LibreELEC.tv/tree/master/projects/Allwinner/patches/linux).

If you switch CODEC_DEBUG in Makefile in the log should be:
"CodecVideoOpen: HW codec drm found"

**Comment by chaseadam** [comment]
Thanks for the direction! Will start exploring with LibreELEC as the A64+ has good support.
